### ISSUE TITLE
[1.16.5] last Seasonhud v1.4.18 does not show sub season

### ISSUE THREAD

**Issue by zanecek** [lanAnderson/SeasonInfo#40]
Setting "enable_show_sub_season = true" does not work, always show only "Spring" and so on.

I use last SereneSeasons v4.0.1.130 and last Xaeros_Minimap-23.7.0.

Thx for help.

**Comment by lanAnderson** [comment]
Should be fixed in 1.4.19 that is currently uploading

**Comment by zanecek** [comment]
Unfortunately the new version 1.4.19 doesn't work either.
Always "Winter, Day 3" instead of "Early Winter, Day 3".

The only change is that the settings "enable_show_minimap_hidden = true" don't work well now.
Will completely cancel the display of the season on the (enabled) minimap.

**Comment by lanAnderson** [comment]
Can you provide a full modlist? I didn't see that when I tested

**Comment by zanecek** [comment]
Thank you for your interest in this.

F.e., now is MID_WINTER, day 0/4.
When "enable_show_sub_season = true" is showing "Winter, Day 1".
When "enable_show_sub_season = false" is showing "Winter, Day 5".

[mod-list_2023-09-09_06.42.25.txt](https://github.com/lanAnderson/SeasonHUD/files/12564599/mod-list_2023-09-09_06.42.25.txt)

**Comment by lanAnderson** [comment]
I saw in another log you posted that your language is set to Czech, and that was what caused it. Version 1.4.20 should fix the issue, and is uploading now

**Comment by zanecek** [comment]
Setting "enable_show_sub_season" now works good, thank you very much.

But setting "enable_show_minimap_hidden = true" doesn't work well now (the error occurred from version 1.14.19).
Will completely cancel the display of the season.

And setting "enable_show_tropical_season = true" doesn't work in my opinion, in the desert I would expect "Early Dry, Day 3" but it still shows "Early Winter, Day 3".
